### PR TITLE
bump netty version

### PR DESCRIPTION
**Pull request by ylgrgyq**
There's [a bug fix](https://github.com/netty/netty/issues/5372) in this version. 

Thanks for this great lib. :wink:

### CODE REVIEW

**Comment by jchambers** [comment]
Huh… this seems to not work with `netty-tcnative`. Maybe we need to bump the version of tcnative to fork18, too?

**Comment by jchambers** [comment]
(and thanks, as always for the contribution and kind words!)

**Comment by ylgrgyq** [comment]
Done. 👍

**Comment by jchambers** [comment]
Thanks again!

**Pull request merged**
