### PR TITLE
[add]support retry mechanism when acquiring channel or sending notification fail

### PR DESCRIPTION
**Pull request by qiankunli**
add code to ApnsClient class:
1. add a queue to save the PushNotificationPromise if send it fail
2. add a period task to consume PushNotificationPromise in the queue

### CODE REVIEW

**Comment by jasonjoo2010** [comment]
it is suggested doing the retry in upper logic.
In best practice we will add semaphore like traffic quotation. Will it be invalid if we had many failed msgs in some condition?

**Comment by qiankunli** [comment]
I just retry to send notification when acquiring channel fail or sending/writing fail which we can make sure that the notification must not be sent to Client. it is difficult to make the choice in upper logic.

I have tried to use CountDownLatch or guava-RateLimiter to realize Rate-Limiting, but there also is a lot of exception like Http2ChannelClosedException

**Comment by qiankunli** [comment]
@jasonjoo2010 Can I add your WeChat, so that we can communicate more about APNs.

**Comment by jasonjoo2010** [comment]
@qiankunli sure. jason_joo

I know what point you are meaning to now, but actually we rarely meet this now.

**Comment by jchambers** [comment]
@qiankunli I'm EXTREMELY sorry to have let this sit for so long. Thank you very much for the contribution!

I definitely understand the need you're trying to address here, but I think this is complexity better left outside of Pushy (i.e. let callers decide how to handle this situation) for now.

Again, thank you very much for this thoughtful contribution, and I'm very sorry to have taken so long to respond.

**Pull request closed without merging**
