### PR TITLE
Drop ALPN in favor of direct protocol negotiation

### PR DESCRIPTION
**Pull request by jchambers**
As [discussed on the mailing list](https://groups.google.com/d/msg/pushy-apns/P-RytjMRVYE/sZA2OkmlAwAJ), it turns out that we can just do direct protocol negotiation instead of using ALPN. This is ironic/semi-funny given how much woe and heartache ALPN has caused us and our users thus far, although the situation HAS been much better since we started relying directly on netty-tcnative.

Still, this is some baggage I'm happy to part with.

### CODE REVIEW

**Comment by flozano** [comment]
Does this mean that we can drop netty-tcnative dependency? also, from the commit, it'd be great if we could configure it with java system properties instead (in addition?) of env variables.

**Comment by jchambers** [comment]
> Does this mean that we can drop netty-tcnative dependency?

I would say "mostly yes," but I'd like to ease into that. After this, I think we can mostly view native SSL providers as optional (but still very helpful!), which would make it easier for end users to pick and choose between, say, netty-tcnative and Conscrypt. Also, the ciphers we need for HTTP/2 weren't widely added to the JDK until Java 8, so I'd say a native provider is still required-ish for Java 7, but not at all for Java 8.

> it'd be great if we could configure it with java system properties instead (in addition?) of env variables.

Interesting. Can you tell me more about the use case? The environment variable thing is largely a hack to support testing in CI environments, and I didn't imagine people would need it in the real world. I think this would only really be useful in cases where you have a native provider on the classpath, but don't want to use it for some reason. I'm not sure (a) why folks wouldn't want to use the native provider or (b) how often folks wind up in a situation where they want the JDK provider, but can't remove the native provider from the classpath. That doesn't mean the use case isn't legit, to be clear! It just means it's something I'll need help to understand.

Thanks!

**Comment by flozano** [comment]
Well, basically it would be an attempt to avoid the TLS reconnection memory leak that has been reported in https://github.com/relayrides/pushy/issues/425.

**Comment by jchambers** [comment]
Hm. Unless you know something I don't, I'm not sure that we've conclusively shown that #425 is a reconnection issue (my kingdom for enough consecutive hours to set up a real experiment and debug that thoroughly). (EDIT: just saw your edit).

Either way, though, couldn't you just exclude the netty-tcnative dependency?

**Comment by jchambers** [comment]
@flozano I'm going to go ahead and merge this so we can start testing with our own systems before releasing publicly. If you still need more tools for selecting an SSL provider at runtime, could you please open a new issue?

Thanks kindly!

**Pull request merged**
