### PR TITLE
Token authentication

### PR DESCRIPTION
**Pull request by jchambers**
This is a work-in-progress branch for token authentication (see #314). The goal here is to take what we know now (which isn't a whole lot) and build some foundations so we can move quickly when the Real Thing™ happens "later this year."

So far, this has mostly been a demolition effort, since we know clients won't need to authenticate when connecting to a server.

### CODE REVIEW

**Comment by gabek** [comment]
Really looking forward to this!

**Comment by peter-allday** [comment]
Hi, any idea when this will be released? I have just received the "Certificate expiring in 30 days" email, and the idea of replacing it with Tokens that don't expire is very appealing.
Thanks
Peter

**Comment by jchambers** [comment]
As mentioned in #314, I've just returned from vacation and hope to finish this shortly.

**Comment by peter-allday** [comment]
Sorry, don't know how I missed your earlier comment. Hope you enjoyed your
vacation.

**Comment by Tolsi** [comment]
So, when this will happen? :)

**Comment by vader** [comment]
Just to let people know when your certificate expires you can still generate a new certificate. That functionality on Apple has not changed albeit that its not that obvious on their dashboard anymore. I just renewed my certificate after an initial panic that I will have to move to tokens before I was ready. Saying that I can't wait to get away from yearly expiring tokens.

**Comment by matzew** [comment]
any comments on landing this ?

**Comment by jchambers** [comment]
> any comments on landing this ?

Situation is still the same; just need to punch it through as soon as other priorities allow, which I'm hoping will be very soon.

**Comment by jchambers** [comment]
Following discussion in #314, I'm going to close this in favor of #397, which is essentially the same thing we have here except with support for TLS-based client authentication.

**Pull request closed without merging**
