### PR TITLE
Memory and synchronization improvements

### PR DESCRIPTION
**Pull request by Nowheresly**
Make static inner classes of FeedbackServiceConnection
Use of AtomicInteger for ApnsConnection.pendingWriteCount to ensure synchronization correctness.

### CODE REVIEW

**Comment by Nowheresly** [comment]
I can see why inner classes `FeedbackServiceConnection.ExpiredTokenDecoder` and `FeedbackServiceConnection.FeedbackClientHandler` could not be declared as static.
Accordingly the gain in memory consumption (two hidden pointers to the enclosing class) is very low.

The second modification is related to the field `ApnsConnection.pendingWriteCount`.
As far as I can see, it is sometimes read by using a lock on pendingWriteMonitor (see method `ApnsConnection.waitForPendingWritesToFinish`) and sometimes read/written using a lock on ApnsConnection (see `ApnsConnection.sendNotification`).
Since this field is not declared as `volatile`, I think this could lead to synchronization issues.
Any thoughts ?
In my PR, I choose to use an `AtomicInteger` instead of declaring it as `volatile`.

**Comment by jmason** [comment]
+1 to using an AtomicInteger just to remove the potential risk.

I would suggest though that a cleaner fix might be to replace the pendingWriteCount and pendingWriteMonitor with a Semaphore, which has the semantics we want here.

**Comment by jchambers** [comment]
> …a Semaphore, which has the semantics we want here.

Forgive me if I'm being dense here (it *is* Friday night), but could you elaborate on that point? I'm struggling to work out when we'd `acquire` and `release` (or maybe what our initial count would be?) to make that work.

Let me be clear, though: if there *is* a way to de-terrible-ize this thing with more standard concurrency tools, I'm all for it ;)

**Comment by Nowheresly** [comment]
Maybe we could consider the use of semaphore to improve the current implementation as a different issue. Why not creating a new issue tagged as "enhancement" dedicated to this ?

**Comment by jchambers** [comment]
> Why not creating a new issue tagged as "enhancement" dedicated to this?

We may wind up doing that in the end, but since we're already considering changing how we're handling pending writing counts, it seems reasonable to consider alternative approaches.

**Comment by jmason** [comment]
actually, never mind me -- I've just taken a look, and yep, without a statically-sized pool of permits to start with I don't think a Semaphore would work here.  my mistake!

**Comment by jchambers** [comment]
> without a statically-sized pool of permits to start with I don't think a Semaphore would work here.

Okay. Thanks for looking into it!

@Nowheresly This looks pretty good to me. Now that we have a `final AtomicInteger`, though, it seems like it might make sense to drop the existing `pendingWriteMonitor` and synchronize on the new `AtomicInteger` in `waitForPendingWritesToFinish` instead. Seem legit?

**Pull request closed without merging**
