### PR TITLE
Flexible notification topic

### PR DESCRIPTION
**Pull request by SamuelHFerreira**
There is now a load from certificate for those that doesn't want to inform the topic but just use the  at ApnsPushNotification, 
-Topic now can be null, when it happens, automatically uses the certificate UID.

### CODE REVIEW

**Comment by jchambers** [comment]
First and foremost, thanks very much for the contribution!

Regrettably, I think we may have to pass on this one. The next big protocol update from Apple introduces authentication tokens (see #314 for additional discussion). One of the big changes there is that we'll be working with keys instead of certificates as our main unit of identity-verification currency. Unlike certificates, keys generally don't have any metadata attached to them, so we probably won't be able to get (for example) a topic list from the signing keys that we'll be working with in the near future.

Since working with keys will almost certainly mean that users will need to be *more* disciplined about topics in the near future, I'd rather not introduce a feature that allows users to be more lax with topics that we'll just have to revert in a couple months.

Does that make sense to you?

Thanks again!

**Comment by jchambers** [comment]
@SamuelHFerreira Again, with sincere thanks for the contribution, I'm going to go ahead and close this for now. Please do post a comment here if you object and we'll revisit.

Cheers!

**Comment by SamuelHFerreira** [comment]
Thank you for the feedback,
i didn't realize that change from Apple, that should be interesting at the next improvement step of this lib,

**Comment by jchambers** [comment]
Awesome. Thank you again!

**Pull request closed without merging**
