### PR TITLE
Added Apn Push Type: Location

### PR DESCRIPTION
**Pull request by fairEnough83**
This PR adds the newly introduced Push Type for location. This is available since ios 15.

### CODE REVIEW

**Comment by jchambers** [comment]
Thanks for the contribution!

**Comment by jchambers** [comment]
…though I'm trying to figure out why the automated checks haven't run for this. I'll get that sorted and then get this merged shortly.

**Comment by fairEnough83** [comment]
@jchambers thanks. fyi. with my exported jar the location push works well on prod!

**Comment by jchambers** [comment]
Mystery solved: I hadn't configred tests to run on external pull requests. At your convenience, could you please:

1. Rebase these changes on to `master`? This will cause your branch to "notice" the configuration change and cause tests to run.
2. Squash everything down to one commit? If this isn't something you're comfortable with, don't worry about it; I can take care of it at merge time.

Thanks!

**Comment by fairEnough83** [comment]
@jchambers i fetched and merged master from your repo to mine. You have to approve that the workflow is started in this case. 

Regards the second. You can easily select squash commits -> as merge option of the pr (it's just one additional click), sounds good?

Best,
Stephan

**Pull request merged**
